In [91]:
#Install required packages
%pip install -U pandas numpy scikit-learn matplotlib seaborn mlflow openpyxl pyyaml ydata-profiling joblib

Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.2.3)
Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\lenovo\anaconda3\lib\site-packages (2.1.3)
Collecting numpy
  Downloading numpy-2.5.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: scikit-learn in c:\users\lenovo\anaconda3\lib\site-packages (1.6.1)
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: matplotlib in c:\users\lenovo\anaconda3\lib\site-packages (3.10.0)
Collecting matplotlib
  Downloading matplotlib-3.11.1-cp313-cp313-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: seaborn in c:\users\lenovo\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: mlflow in c:\users\lenovo\anaconda3\lib\site-packages (3.15.2)
Requirement already satisfied: openpyxl in c:\users\lenovo\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: pyyaml in c:\users\lenovo\anaconda3\lib\site-packages (6.0.3)
Requirement already satisfied: ydata-profiling in c:\users\lenovo\anaconda3\lib\site-packages (4.18.4)
Requirement already satisfied: joblib in c:\users\lenovo\anaconda3\lib\site-packages (1.4.2)
Collecting joblib
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.25.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=9 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: mlflow-skinny==3.15.2 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (3.15.2)
Requirement already satisfied: mlflow-tracing==3.15.2 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (3.15.2)
Requirement already satisfied: Flask-CORS<7 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (6.0.5)
Requirement already satisfied: Flask<4 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (3.1.0)
Requirement already satisfied: aiohttp<4,>=3.7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (3.11.10)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (1.18.5)
Requirement already satisfied: cryptography<50,>=43.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (44.0.1)
Requirement already satisfied: docker<8,>=4.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (7.2.0)
Requirement already satisfied: graphene<4 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: huey<4,>=2.5.4 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (3.3.4)
Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: pyarrow<26,>=4.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (19.0.0)
Requirement already satisfied: skops<1 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (2.0.39)
Requirement already satisfied: waitress<4 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (8.5.0)
Requirement already satisfied: cloudpickle<4 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (3.0.0)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (0.133.0)
Requirement already satisfied: fastapi<1 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (0.141.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (3.1.43)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (8.5.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (1.44.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (1.44.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (1.44.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (6.33.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (2.10.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (1.1.0)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (2.32.3)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (0.6.0)
Requirement already satisfied: starlette<2 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (1.6.0)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (4.16.0)
Requirement already satisfied: uvicorn<1 in c:\users\lenovo\anaconda3\lib\site-packages (from mlflow-skinny==3.15.2->mlflow) (0.52.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.18.0)
Requirement already satisfied: Mako in c:\users\lenovo\anaconda3\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: cffi>=1.12 in c:\users\lenovo\anaconda3\lib\site-packages (from cryptography<50,>=43.0.0->mlflow) (2.1.1)
Requirement already satisfied: google-auth~=2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.2->mlflow) (2.57.0)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\lenovo\anaconda3\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.2->mlflow) (2.3.0)
Requirement already satisfied: pywin32>=304 in c:\users\lenovo\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (308)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\lenovo\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.15.2->mlflow) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\lenovo\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.15.2->mlflow) (0.0.5)
Requirement already satisfied: Werkzeug>=3.1 in c:\users\lenovo\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.3)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\lenovo\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: itsdangerous>=2.2 in c:\users\lenovo\anaconda3\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.9 in c:\users\lenovo\anaconda3\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.15.2->mlflow) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.15.2->mlflow) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\lenovo\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.2->mlflow) (0.2.8)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\lenovo\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.12)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\users\lenovo\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: zipp>=3.20 in c:\users\lenovo\anaconda3\lib\site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.15.2->mlflow) (3.21.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.65b0 in c:\users\lenovo\anaconda3\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.15.2->mlflow) (0.65b0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.2->mlflow) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.2->mlflow) (2.27.1)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.2->mlflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.2->mlflow) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.2->mlflow) (2026.7.22)
Collecting numpy
  Downloading numpy-2.4.6-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: prettytable>=3.9 in c:\users\lenovo\anaconda3\lib\site-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.1.1)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\lenovo\anaconda3\lib\site-packages (from starlette<2->mlflow-skinny==3.15.2->mlflow) (4.7.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\lenovo\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette<2->mlflow-skinny==3.15.2->mlflow) (1.3.0)
Requirement already satisfied: h11>=0.8 in c:\users\lenovo\anaconda3\lib\site-packages (from uvicorn<1->mlflow-skinny==3.15.2->mlflow) (0.16.0)
Requirement already satisfied: et-xmlfile in c:\users\lenovo\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\lenovo\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
  Downloading numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=4 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\lenovo\anaconda3\lib\site-packages (from ydata-profiling) (0.61.0)
Requirement already satisfied: PyWavelets in c:\users\lenovo\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from Jinja2>=3.1.2->Flask<4->mlflow) (3.0.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in c:\users\lenovo\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\lenovo\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: networkx>=2.4 in c:\users\lenovo\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Requirement already satisfied: puremagic in c:\users\lenovo\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: pycparser in c:\users\lenovo\anaconda3\lib\site-packages (from cffi>=1.12->cryptography<50,>=43.0.0->mlflow) (2.21)
Requirement already satisfied: wcwidth>=0.3.5 in c:\users\lenovo\anaconda3\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\lenovo\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.2->mlflow) (0.4.8)
Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.2 MB 5.1 MB/s eta 0:00:02
   -------- ------------------------------- 1.8/8.2 MB 5.0 MB/s eta 0:00:02
   -------------- ------------------------- 2.9/8.2 MB 5.1 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.2 MB 5.3 MB/s eta 0:00:01
   -------------------------- ------------- 5.5/8.2 MB 5.5 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 5.7 MB/s eta 0:00:00
Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/11.0 MB 7.1 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/11.0 MB 6.9 MB/s eta 0:00:02
   -------------- ------------------------- 3.9/11.0 MB 6.8 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.0 MB 6.9 MB/s eta 0:00:01
   ----------------------- ---------------- 6.6/11.0 MB 6.7 MB/s eta 0:00:01
   ---------------------------- ----------- 7.9/11.0 MB 6.2 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.0 MB 6.1 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 5.8 MB/s eta 0:00:00
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading narwhals-2.25.0-py3-none-any.whl (467 kB)
Installing collected packages: narwhals, joblib, scikit-learn, pandas

  Attempting uninstall: narwhals

    Found existing installation: narwhals 1.31.0

   ---------------------------------------- 0/4 [narwhals]
    Uninstalling narwhals-1.31.0:
   ---------------------------------------- 0/4 [narwhals]
      Successfully uninstalled narwhals-1.31.0
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
  Attempting uninstall: joblib
   ---------------------------------------- 0/4 [narwhals]
   ---------- ----------------------------- 1/4 [joblib]
    Found existing installation: joblib 1.4.2
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
    Uninstalling joblib-1.4.2:
   ---------- ----------------------------- 1/4 [joblib]
      Successfully uninstalled joblib-1.4.2
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.9.0 which is incompatible.

   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ---------------------------------------- 4/4 [pandas]

Successfully installed joblib-1.6.0 narwhals-2.25.0 pandas-2.3.3 scikit-learn-1.9.0

In [1]:
#Check Python and package versions
import sys
import pandas as pd
import numpy as np
import sklearn
import mlflow

print("=" * 60)
print("ENVIRONMENT CHECK")
print("=" * 60)

print("Python version :", sys.version)
print("Pandas version :", pd.__version__)
print("NumPy version  :", np.__version__)
print("Scikit-learn   :", sklearn.__version__)
print("MLflow version  :", mlflow.__version__)

print("\nEnvironment is ready.")

============================================================
ENVIRONMENT CHECK
============================================================
Python version : 3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]
Pandas version : 2.3.3
NumPy version  : 2.1.3
Scikit-learn   : 1.9.0
MLflow version  : 3.15.2

Environment is ready.

In [2]:
#Create project folders
from pathlib import Path

BASE_DIR = Path.cwd()

folders = [
    "models",
    "reports",
    "data",
    "artifacts",
    "mlartifacts"
]

for folder in folders:
    Path(folder).mkdir(exist_ok=True)

print("Project directory:")
print(BASE_DIR)

print("\nFolders created:")
for folder in folders:
    print("✓", folder)

Project directory:
C:\Users\LENOVO\Sales_MLOPS

Folders created:
✓ models
✓ reports
✓ data
✓ artifacts
✓ mlartifacts

In [3]:
#Find your sales CSV
from pathlib import Path

csv_files = list(Path(".").glob("*.csv"))

print("CSV files found:\n")

if not csv_files:
    print("NO CSV FILE FOUND.")
    print("Put your sales CSV inside the same folder as this notebook.")
else:
    for i, file in enumerate(csv_files, start=1):
        print(f"{i}. {file}")

CSV files found:

1. sales_data.csv

In [4]:
#Load the dataset
import pandas as pd
from pathlib import Path

csv_files = list(Path(".").glob("*.csv"))

if len(csv_files) == 0:
    raise FileNotFoundError(
        "No CSV file found. Put your sales dataset in the notebook folder."
    )

# Automatically select the first CSV
DATA_FILE = csv_files[0]

df = pd.read_csv(DATA_FILE)

print("=" * 70)
print("DATA INGESTION")
print("=" * 70)

print("Selected file:", DATA_FILE)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

display(df.head(10))

======================================================================
DATA INGESTION
======================================================================
Selected file: sales_data.csv
Rows: 1000
Columns: 14

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
5,1021,2023-02-11,Charlie,West,3761.15,32,Food,900.79,1106.51,New,0.21,Cash,Online,West-Charlie
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
8,1075,2023-06-29,David,South,4223.39,30,Furniture,738.06,1095.45,New,0.05,Bank Transfer,Online,South-David
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie

In [5]:
from IPython.display import display

print("=" * 70)
print("DATASET INFORMATION")
print("=" * 70)

print("\nShape:")
print(df.shape)

print("\nColumn names:")
for col in df.columns:
    print("•", col)

print("\nData types:")
display(df.dtypes.to_frame("Data Type"))

print("\nFirst 10 rows:")
display(df.head(10))

======================================================================
DATASET INFORMATION
======================================================================

Shape:
(1000, 14)

Column names:
• Product_ID
• Sale_Date
• Sales_Rep
• Region
• Sales_Amount
• Quantity_Sold
• Product_Category
• Unit_Cost
• Unit_Price
• Customer_Type
• Discount
• Payment_Method
• Sales_Channel
• Region_and_Sales_Rep

Data types:

                     Data Type
Product_ID               int64
Sale_Date               object
Sales_Rep               object
Region                  object
Sales_Amount           float64
Quantity_Sold            int64
Product_Category        object
Unit_Cost              float64
Unit_Price             float64
Customer_Type           object
Discount               float64
Payment_Method          object
Sales_Channel           object
Region_and_Sales_Rep    object

First 10 rows:

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
5,1021,2023-02-11,Charlie,West,3761.15,32,Food,900.79,1106.51,New,0.21,Cash,Online,West-Charlie
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
8,1075,2023-06-29,David,South,4223.39,30,Furniture,738.06,1095.45,New,0.05,Bank Transfer,Online,South-David
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie

In [6]:
TARGET_CANDIDATES = [
    "Sales Amount",
    "SalesAmount",
    "Sales_Amount",
    "Sales",
    "sales",
    "Salary",
    "salary",
    "Employee Salary",
    "Employee_Salary",
    "Amount",
    "amount",
    "Revenue",
    "revenue"
]

def find_target_column(columns):
    normalized = {
        str(col).strip().lower().replace("_", " ").replace("-", " "): col
        for col in columns
    }

    for candidate in TARGET_CANDIDATES:
        key = candidate.lower().replace("_", " ").replace("-", " ")
        if key in normalized:
            return normalized[key]

    return None


TARGET_COLUMN = find_target_column(df.columns)

print("Target column detected:", TARGET_COLUMN)

if TARGET_COLUMN is None:
    print("\nCould not automatically detect the target.")
    print("Available columns:")
    print(list(df.columns))
    print("\nSet TARGET_COLUMN manually, for example:")
    print('TARGET_COLUMN = "Sales Amount"')
else:
    print("Target column:", TARGET_COLUMN)

Target column detected: Sales_Amount
Target column: Sales_Amount

In [7]:
TARGET_COLUMN = "Sales_Amount"

In [8]:
#Data profiling
print("=" * 70)
print("DATA PROFILING")
print("=" * 70)

print("\nBasic statistics:")
display(df.describe(include="all").T)

print("\nMissing values:")
missing = df.isnull().sum().sort_values(ascending=False)
display(missing.to_frame("Missing Values"))

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nUnique values:")
display(df.nunique().sort_values(ascending=False).to_frame("Unique Values"))

======================================================================
DATA PROFILING
======================================================================

Basic statistics:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Product_ID,1000.0,NaN,NaN,NaN,1050.128,29.573505,1001.0,1024.0,1051.0,1075.0,1100.0
Sale_Date,1000,340,2023-11-14,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sales_Rep,1000,5,David,222,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Region,1000,4,North,267,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sales_Amount,1000.0,NaN,NaN,NaN,5019.26523,2846.790126,100.12,2550.2975,5019.3,7507.445,9989.04
Quantity_Sold,1000.0,NaN,NaN,NaN,25.355,14.159006,1.0,13.0,25.0,38.0,49.0
Product_Category,1000,4,Clothing,268,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unit_Cost,1000.0,NaN,NaN,NaN,2475.30455,1417.872546,60.28,1238.38,2467.235,3702.865,4995.3
Unit_Price,1000.0,NaN,NaN,NaN,2728.44012,1419.399839,167.12,1509.085,2696.4,3957.97,5442.15
Customer_Type,1000,2,New,504,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discount,1000.0,NaN,NaN,NaN,0.15239,0.0872,0.0,0.08,0.15,0.23,0.3
Payment_Method,1000,3,Credit Card,345,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sales_Channel,1000,2,Retail,512,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Region_and_Sales_Rep,1000,20,North-Eve,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Missing values:

                      Missing Values
Product_ID                         0
Sale_Date                          0
Sales_Rep                          0
Region                             0
Sales_Amount                       0
Quantity_Sold                      0
Product_Category                   0
Unit_Cost                          0
Unit_Price                         0
Customer_Type                      0
Discount                           0
Payment_Method                     0
Sales_Channel                      0
Region_and_Sales_Rep               0

Duplicate rows:
0

Unique values:

                      Unique Values
Unit_Price                     1000
Sales_Amount                    998
Unit_Cost                       998
Sale_Date                       340
Product_ID                      100
Quantity_Sold                    49
Discount                         31
Region_and_Sales_Rep             20
Sales_Rep                         5
Region                            4
Product_Category                  4
Payment_Method                    3
Customer_Type                     2
Sales_Channel                     2

In [9]:
#Generate profiling report
from ydata_profiling import ProfileReport

print("Creating data profiling report...")

profile = ProfileReport(
    df,
    title="Sales Dataset - Data Profiling Report",
    explorative=True
)

profile.to_file("reports/data_profile.html")

print("✓ Profiling report created:")
print("reports/data_profile.html")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_25004\711174723.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Creating data profiling report...

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 192.42it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

✓ Profiling report created:
reports/data_profile.html

In [10]:
from IPython.display import IFrame, display

display(
    IFrame(
        src="reports/data_profile.html",
        width="100%",
        height=700
    )
)

In [11]:
#Data validation
print("=" * 70)
print("DATA VALIDATION")
print("=" * 70)

validation_results = {}

validation_results["Rows"] = len(df)
validation_results["Columns"] = len(df.columns)
validation_results["Duplicate Rows"] = int(df.duplicated().sum())
validation_results["Missing Cells"] = int(df.isnull().sum().sum())
validation_results["Target Exists"] = TARGET_COLUMN in df.columns

validation_df = pd.DataFrame(
    list(validation_results.items()),
    columns=["Validation Check", "Result"]
)

display(validation_df)

if TARGET_COLUMN not in df.columns:
    raise ValueError(
        f"Target column '{TARGET_COLUMN}' does not exist."
    )

print("\n✓ Target column validation passed.")

======================================================================
DATA VALIDATION
======================================================================

  Validation Check Result
0             Rows   1000
1          Columns     14
2   Duplicate Rows      0
3    Missing Cells      0
4    Target Exists   True

✓ Target column validation passed.

In [12]:
#Data cleaning
print("=" * 70)
print("DATA ENGINEERING / CLEANING")
print("=" * 70)

data = df.copy()

# Remove completely empty rows
data = data.dropna(how="all")

# Remove duplicate rows
before_duplicates = len(data)
data = data.drop_duplicates()
after_duplicates = len(data)

# Convert target to numeric
data[TARGET_COLUMN] = pd.to_numeric(
    data[TARGET_COLUMN],
    errors="coerce"
)

# Remove rows where target is missing
before_target = len(data)
data = data.dropna(subset=[TARGET_COLUMN])
after_target = len(data)

print("Original rows:", len(df))
print("Removed duplicates:", before_duplicates - after_duplicates)
print("Removed missing target rows:", before_target - after_target)
print("Final rows:", len(data))

display(data.head(10))

======================================================================
DATA ENGINEERING / CLEANING
======================================================================
Original rows: 1000
Removed duplicates: 0
Removed missing target rows: 0
Final rows: 1000

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
5,1021,2023-02-11,Charlie,West,3761.15,32,Food,900.79,1106.51,New,0.21,Cash,Online,West-Charlie
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
8,1075,2023-06-29,David,South,4223.39,30,Furniture,738.06,1095.45,New,0.05,Bank Transfer,Online,South-David
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie

In [13]:
#Feature engineering
print("=" * 70)
print("FEATURE ENGINEERING")
print("=" * 70)

feature_data = data.copy()

# Remove target from features
X = feature_data.drop(columns=[TARGET_COLUMN])
y = feature_data[TARGET_COLUMN]

print("Target:", TARGET_COLUMN)

print("\nFeature columns:")
for col in X.columns:
    print("•", col)

print("\nTarget statistics:")
display(y.describe().to_frame("Target"))

print("\nFeature dataset:")
display(X.head())

======================================================================
FEATURE ENGINEERING
======================================================================
Target: Sales_Amount

Feature columns:
• Product_ID
• Sale_Date
• Sales_Rep
• Region
• Quantity_Sold
• Product_Category
• Unit_Cost
• Unit_Price
• Customer_Type
• Discount
• Payment_Method
• Sales_Channel
• Region_and_Sales_Rep

Target statistics:

            Target
count  1000.000000
mean   5019.265230
std    2846.790126
min     100.120000
25%    2550.297500
50%    5019.300000
75%    7507.445000
max    9989.040000

Feature dataset:

,Product_ID,Sale_Date,Sales_Rep,Region,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [15]:
#Save processed data
processed_path = Path("processed_sales.csv")

feature_data.to_csv(
    processed_path,
    index=False
)

print("✓ Processed data saved:")
print(processed_path)

✓ Processed data saved:
processed_sales.csv

In [16]:
#Determine numeric/categorical columns
numeric_features = X.select_dtypes(
    include=["int64", "int32", "float64", "float32"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("=" * 70)
print("FEATURE ANALYSIS")
print("=" * 70)

print("\nNumeric features:")
for col in numeric_features:
    print("•", col)

print("\nCategorical features:")
for col in categorical_features:
    print("•", col)

======================================================================
FEATURE ANALYSIS
======================================================================

Numeric features:
• Product_ID
• Quantity_Sold
• Unit_Cost
• Unit_Price
• Discount

Categorical features:
• Sale_Date
• Sales_Rep
• Region
• Product_Category
• Customer_Type
• Payment_Method
• Sales_Channel
• Region_and_Sales_Rep

In [17]:
#Train/Test split
from sklearn.model_selection import train_test_split

TEST_SIZE = 0.20
RANDOM_STATE = 42

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE
)

print("=" * 70)
print("TRAIN / TEST SPLIT")
print("=" * 70)

print("Training rows:", len(X_train))
print("Testing rows :", len(X_test))
print("Test size    :", TEST_SIZE)
print("Random state :", RANDOM_STATE)

======================================================================
TRAIN / TEST SPLIT
======================================================================
Training rows: 800
Testing rows : 200
Test size    : 0.2
Random state : 42

In [18]:
#Preprocessing pipeline
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_transformer, numeric_features),
        ("categorical", categorical_transformer, categorical_features)
    ],
    remainder="drop"
)

print("✓ Preprocessing pipeline created.")

✓ Preprocessing pipeline created.

In [19]:
#Import models
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

models = {
    "Linear Regression": LinearRegression(),

    "Decision Tree": DecisionTreeRegressor(
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestRegressor(
        n_estimators=100,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        random_state=RANDOM_STATE
    )
}

print("Models to train:\n")

for name in models:
    print("•", name)

Models to train:

• Linear Regression
• Decision Tree
• Random Forest
• Gradient Boosting

In [20]:
import mlflow
from pathlib import Path

MLFLOW_DB = Path.cwd() / "mlflow.db"

mlflow.set_tracking_uri(
    f"sqlite:///{MLFLOW_DB.as_posix()}"
)

EXPERIMENT_NAME = "Sales_Prediction"

mlflow.set_experiment(EXPERIMENT_NAME)

print("=" * 70)
print("MLFLOW CONFIGURATION")
print("=" * 70)

print("Tracking URI:")
print(mlflow.get_tracking_uri())

print("\nExperiment:")
print(EXPERIMENT_NAME)

print("\n✓ MLflow connected.")

2026/09/01 15:36:15 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/09/01 15:36:16 INFO mlflow.store.db.utils: Updating database tables
2026/09/01 15:36:21 INFO mlflow.tracking.fluent: Experiment with name 'Sales_Prediction' does not exist. Creating a new experiment.

======================================================================
MLFLOW CONFIGURATION
======================================================================
Tracking URI:
sqlite:///C:/Users/LENOVO/Sales_MLOPS/mlflow.db

Experiment:
Sales_Prediction

✓ MLflow connected.

In [25]:
import mlflow

EXPERIMENT_NAME = "Sales_Prediction"

mlflow.set_experiment(EXPERIMENT_NAME)

print("Experiment:", EXPERIMENT_NAME)
print("Tracking URI:", mlflow.get_tracking_uri())

Experiment: Sales_Prediction
Tracking URI: http://127.0.0.1:5000

In [26]:
import mlflow

with mlflow.start_run(run_name="Connection_Test"):

    mlflow.log_param("test", "Jupyter connected")
    mlflow.log_metric("test_metric", 1.0)

    run_id = mlflow.active_run().info.run_id

print("MLflow connection successful!")
print("Run ID:", run_id)

🏃 View run Connection_Test at: http://127.0.0.1:5000/#/experiments/6/runs/b580bda253f34198a1d698d84f8a648c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6
MLflow connection successful!
Run ID: b580bda253f34198a1d698d84f8a648c

In [31]:
# ============================================================
# CELL 21 - MODEL TRAINING + MLFLOW TRACKING
# CORRECTED FOR MLFLOW 3.15.2
# ============================================================

import mlflow
import mlflow.sklearn

import numpy as np
import pandas as pd
import joblib

from pathlib import Path
from sklearn.base import clone
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# ============================================================
# 1. CONNECT TO EXISTING MLFLOW SERVER
# ============================================================

mlflow.set_tracking_uri(
    "http://127.0.0.1:5000"
)

mlflow.set_experiment(
    "Sales_Prediction"
)

print("=" * 80)
print("CELL 21 - MODEL TRAINING + MLFLOW TRACKING")
print("=" * 80)

print("\nMLflow Tracking URI:")
print(mlflow.get_tracking_uri())

# ============================================================
# 2. CREATE REQUIRED FOLDERS
# ============================================================

Path("models").mkdir(exist_ok=True)
Path("reports").mkdir(exist_ok=True)

# ============================================================
# 3. RESULTS STORAGE
# ============================================================

results = []

# ============================================================
# 4. TRAIN EACH MODEL
# ============================================================

for model_name, original_model in models.items():

    print("\n")
    print("=" * 80)
    print(f"TRAINING: {model_name}")
    print("=" * 80)

    # Create fresh model
    model = clone(original_model)

    # Create fresh preprocessing pipeline
    current_preprocessor = clone(preprocessor)

    # Complete ML pipeline
    pipeline = Pipeline(
        steps=[
            (
                "preprocessor",
                current_preprocessor
            ),
            (
                "model",
                model
            )
        ]
    )

    # ========================================================
    # START MLFLOW RUN
    # ========================================================

    with mlflow.start_run(
        run_name=model_name.replace(" ", "_")
    ):

        # ----------------------------------------------------
        # PARAMETERS
        # ----------------------------------------------------

        mlflow.log_param(
            "model",
            model.__class__.__name__
        )

        mlflow.log_param(
            "test_size",
            TEST_SIZE
        )

        mlflow.log_param(
            "random_state",
            RANDOM_STATE
        )

        if hasattr(model, "n_estimators"):
            mlflow.log_param(
                "n_estimators",
                model.n_estimators
            )

        if hasattr(model, "max_depth"):
            mlflow.log_param(
                "max_depth",
                model.max_depth
            )

        # ----------------------------------------------------
        # TAGS
        # ----------------------------------------------------

        mlflow.set_tag(
            "model_name",
            model_name
        )

        mlflow.set_tag(
            "problem_type",
            "regression"
        )

        mlflow.set_tag(
            "target_column",
            TARGET_COLUMN
        )

        # ----------------------------------------------------
        # TRAIN
        # ----------------------------------------------------

        print("Training model...")

        pipeline.fit(
            X_train,
            y_train
        )

        print("✓ Training completed")

        # ----------------------------------------------------
        # PREDICTION
        # ----------------------------------------------------

        y_pred = pipeline.predict(
            X_test
        )

        print("✓ Prediction completed")

        # ----------------------------------------------------
        # CALCULATE METRICS
        # ----------------------------------------------------

        mae = mean_absolute_error(
            y_test,
            y_pred
        )

        rmse = np.sqrt(
            mean_squared_error(
                y_test,
                y_pred
            )
        )

        r2 = r2_score(
            y_test,
            y_pred
        )

        print("\nMetrics:")
        print(f"MAE  : {mae:.4f}")
        print(f"RMSE : {rmse:.4f}")
        print(f"R²   : {r2:.4f}")

        # ----------------------------------------------------
        # LOG METRICS
        # ----------------------------------------------------

        mlflow.log_metric(
            "MAE",
            float(mae)
        )

        mlflow.log_metric(
            "RMSE",
            float(rmse)
        )

        mlflow.log_metric(
            "R2",
            float(r2)
        )

        print("✓ Metrics logged")

        # ----------------------------------------------------
        # SAVE MODEL LOCALLY
        # ----------------------------------------------------

        model_filename = (
            model_name
            .lower()
            .replace(" ", "_")
            + ".pkl"
        )

        model_path = (
            Path("models") /
            model_filename
        )

        joblib.dump(
            pipeline,
            model_path
        )

        print(
            "✓ Local model saved:",
            model_path
        )

        # ----------------------------------------------------
        # LOG MODEL FILE AS ARTIFACT
        # ----------------------------------------------------

        mlflow.log_artifact(
            str(model_path),
            artifact_path="model_files"
        )

        print("✓ Model artifact logged")

        # ----------------------------------------------------
        # LOG MODEL TO MLFLOW
        #
        # IMPORTANT:
        # Explicitly use pickle to avoid the skops
        # numpy.dtype trust error.
        # ----------------------------------------------------

        print("Logging model to MLflow...")

        mlflow.sklearn.log_model(
            sk_model=pipeline,
            name="model",
            serialization_format="pickle"
        )

        print("✓ Model successfully logged to MLflow")

        # ----------------------------------------------------
        # GET RUN ID
        # ----------------------------------------------------

        run_id = (
            mlflow.active_run()
            .info
            .run_id
        )

        print("Run ID:", run_id)

        # ----------------------------------------------------
        # SAVE RESULT
        # ----------------------------------------------------

        results.append({
            "Run ID": run_id,
            "Model": model_name,
            "MAE": float(mae),
            "RMSE": float(rmse),
            "R2": float(r2)
        })

        print("✓ RUN COMPLETED SUCCESSFULLY")


# ============================================================
# 5. CREATE RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
)

print("\n")
print("=" * 80)
print("ALL MODELS COMPLETED SUCCESSFULLY")
print("=" * 80)

display(
    results_df
)

================================================================================
CELL 21 - MODEL TRAINING + MLFLOW TRACKING
================================================================================

MLflow Tracking URI:
http://127.0.0.1:5000


================================================================================
TRAINING: Linear Regression
================================================================================
Training model...
✓ Training completed
✓ Prediction completed

Metrics:
MAE  : 3266.4725
RMSE : 3840.2188
R²   : -0.5958
✓ Metrics logged
✓ Local model saved: models\linear_regression.pkl
✓ Model artifact logged
Logging model to MLflow...

2026/09/01 16:00:38 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

✓ Model successfully logged to MLflow
Run ID: a5f3699421364857a425d2511c87b931
✓ RUN COMPLETED SUCCESSFULLY
🏃 View run Linear_Regression at: http://127.0.0.1:5000/#/experiments/6/runs/a5f3699421364857a425d2511c87b931
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6


================================================================================
TRAINING: Decision Tree
================================================================================
Training model...
✓ Training completed
✓ Prediction completed

Metrics:
MAE  : 3354.5412
RMSE : 4129.5292
R²   : -0.8453
✓ Metrics logged
✓ Local model saved: models\decision_tree.pkl
✓ Model artifact logged
Logging model to MLflow...

2026/09/01 16:01:08 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

✓ Model successfully logged to MLflow
Run ID: 709d5f8a624742a38a0f392b3217a070
✓ RUN COMPLETED SUCCESSFULLY
🏃 View run Decision_Tree at: http://127.0.0.1:5000/#/experiments/6/runs/709d5f8a624742a38a0f392b3217a070
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6


================================================================================
TRAINING: Random Forest
================================================================================
Training model...
✓ Training completed
✓ Prediction completed

Metrics:
MAE  : 2831.9520
RMSE : 3232.5611
R²   : -0.1307
✓ Metrics logged
✓ Local model saved: models\random_forest.pkl
✓ Model artifact logged
Logging model to MLflow...

2026/09/01 16:01:16 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

✓ Model successfully logged to MLflow
Run ID: 8c259ba3e67846bb80a0bf1f927a1bcc
✓ RUN COMPLETED SUCCESSFULLY
🏃 View run Random_Forest at: http://127.0.0.1:5000/#/experiments/6/runs/8c259ba3e67846bb80a0bf1f927a1bcc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6


================================================================================
TRAINING: Gradient Boosting
================================================================================
Training model...
✓ Training completed
✓ Prediction completed

Metrics:
MAE  : 2781.8100
RMSE : 3157.6616
R²   : -0.0789
✓ Metrics logged
✓ Local model saved: models\gradient_boosting.pkl
✓ Model artifact logged
Logging model to MLflow...

2026/09/01 16:01:24 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

✓ Model successfully logged to MLflow
Run ID: 2a844be6b26647f5b480594adbf99259
✓ RUN COMPLETED SUCCESSFULLY
🏃 View run Gradient_Boosting at: http://127.0.0.1:5000/#/experiments/6/runs/2a844be6b26647f5b480594adbf99259
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6


================================================================================
ALL MODELS COMPLETED SUCCESSFULLY
================================================================================

,Run ID,Model,MAE,RMSE,R2
0,a5f3699421364857a425d2511c87b931,Linear Regression,3266.472460,3840.218813,-0.595798
1,709d5f8a624742a38a0f392b3217a070,Decision Tree,3354.541200,4129.529213,-0.845300
2,8c259ba3e67846bb80a0bf1f927a1bcc,Random Forest,2831.952027,3232.561103,-0.130731
3,2a844be6b26647f5b480594adbf99259,Gradient Boosting,2781.810026,3157.661599,-0.078940

In [32]:
# ============================================================
# CELL 22 - MODEL COMPARISON
# ============================================================

print("=" * 80)
print("CELL 22 - MODEL COMPARISON")
print("=" * 80)

comparison_df = (
    results_df
    .sort_values(
        by="R2",
        ascending=False
    )
    .reset_index(drop=True)
)

display(
    comparison_df.style.format({
        "MAE": "{:.2f}",
        "RMSE": "{:.2f}",
        "R2": "{:.4f}"
    })
)

================================================================================
CELL 22 - MODEL COMPARISON
================================================================================

In [33]:
# ============================================================
# CELL 23 - BEST MODEL SELECTION
# ============================================================

print("=" * 80)
print("CELL 23 - BEST MODEL SELECTION")
print("=" * 80)

best_row = comparison_df.iloc[0]

BEST_MODEL_NAME = best_row["Model"]
BEST_RUN_ID = best_row["Run ID"]
BEST_MAE = best_row["MAE"]
BEST_RMSE = best_row["RMSE"]
BEST_R2 = best_row["R2"]

print("\nBEST MODEL")
print("-" * 50)

print("Model :", BEST_MODEL_NAME)
print("MAE   :", f"{BEST_MAE:.4f}")
print("RMSE  :", f"{BEST_RMSE:.4f}")
print("R²    :", f"{BEST_R2:.4f}")
print("Run ID:", BEST_RUN_ID)

================================================================================
CELL 23 - BEST MODEL SELECTION
================================================================================

BEST MODEL
--------------------------------------------------
Model : Gradient Boosting
MAE   : 2781.8100
RMSE  : 3157.6616
R²    : -0.0789
Run ID: 2a844be6b26647f5b480594adbf99259

In [34]:
# ============================================================
# CELL 24 - SAVE MODEL COMPARISON
# ============================================================

from pathlib import Path

print("=" * 70)
print("CELL 24 - SAVE MODEL COMPARISON")
print("=" * 70)

# Create reports folder
Path("reports").mkdir(exist_ok=True)

# Save comparison table
comparison_df.to_csv(
    "reports/model_comparison.csv",
    index=False
)

print("✓ Model comparison saved successfully.")
print("File: reports/model_comparison.csv")

display(comparison_df)

======================================================================
CELL 24 - SAVE MODEL COMPARISON
======================================================================
✓ Model comparison saved successfully.
File: reports/model_comparison.csv

,Run ID,Model,MAE,RMSE,R2
0,2a844be6b26647f5b480594adbf99259,Gradient Boosting,2781.810026,3157.661599,-0.078940
1,8c259ba3e67846bb80a0bf1f927a1bcc,Random Forest,2831.952027,3232.561103,-0.130731
2,a5f3699421364857a425d2511c87b931,Linear Regression,3266.472460,3840.218813,-0.595798
3,709d5f8a624742a38a0f392b3217a070,Decision Tree,3354.541200,4129.529213,-0.845300

In [35]:
# ============================================================
# CELL 25 - LOAD BEST MODEL
# ============================================================

import joblib
from pathlib import Path

print("=" * 70)
print("CELL 25 - LOAD BEST MODEL")
print("=" * 70)

# Convert model name to filename
best_model_filename = (
    BEST_MODEL_NAME
    .lower()
    .replace(" ", "_")
    + ".pkl"
)

best_model_path = (
    Path("models") /
    best_model_filename
)

print("Best Model:")
print(BEST_MODEL_NAME)

print("\nModel File:")
print(best_model_path)

# Check whether file exists
if not best_model_path.exists():
    raise FileNotFoundError(
        f"Best model file not found: {best_model_path}"
    )

# Load model
best_model = joblib.load(
    best_model_path
)

print("\n✓ Best model loaded successfully.")

======================================================================
CELL 25 - LOAD BEST MODEL
======================================================================
Best Model:
Gradient Boosting

Model File:
models\gradient_boosting.pkl

✓ Best model loaded successfully.

In [36]:
# ============================================================
# CELL 26 - PREDICTION
# ============================================================

print("=" * 70)
print("CELL 26 - PREDICTION")
print("=" * 70)

# Generate predictions
best_predictions = best_model.predict(
    X_test
)

# Create prediction table
prediction_df = X_test.copy()

prediction_df["Actual"] = y_test.values

prediction_df["Predicted"] = best_predictions

prediction_df["Error"] = (
    prediction_df["Actual"]
    - prediction_df["Predicted"]
)

print("✓ Predictions generated successfully.")

print("\nFirst 20 predictions:")

display(
    prediction_df.head(20)
)

======================================================================
CELL 26 - PREDICTION
======================================================================
✓ Predictions generated successfully.

First 20 predictions:

,Product_ID,Sale_Date,Sales_Rep,Region,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep,Actual,Predicted,Error
521,1100,2023-05-23,Bob,West,29,Food,3559.56,3607.15,Returning,0.21,Cash,Retail,West-Bob,7667.96,5373.761795,2294.198205
737,1031,2023-03-23,Eve,East,32,Clothing,3351.33,3711.47,New,0.16,Cash,Retail,East-Eve,433.40,3916.143807,-3482.743807
740,1003,2023-07-25,Eve,West,5,Food,2206.58,2490.47,New,0.28,Cash,Online,West-Eve,5617.64,4668.237826,949.402174
660,1017,2023-12-23,Alice,East,33,Food,1551.25,1994.01,Returning,0.08,Cash,Online,East-Alice,780.27,4799.410664,-4019.140664
411,1042,2023-05-26,Bob,East,1,Electronics,1406.24,1535.57,New,0.08,Credit Card,Retail,East-Bob,848.28,4522.511394,-3674.231394
678,1017,2023-02-07,Charlie,West,2,Food,728.41,1094.92,New,0.24,Cash,Retail,West-Charlie,7542.30,4461.530613,3080.769387
626,1028,2023-08-31,Eve,North,28,Furniture,2055.28,2449.64,New,0.19,Credit Card,Online,North-Eve,5403.00,4956.913747,446.086253
513,1069,2023-05-29,Alice,North,30,Electronics,300.01,477.68,New,0.11,Bank Transfer,Retail,North-Alice,4494.80,4929.459140,-434.659140
859,1075,2023-06-15,Eve,North,26,Furniture,1749.34,1935.25,New,0.14,Credit Card,Online,North-Eve,9736.49,4931.882435,4804.607565
136,1099,2023-03-04,David,East,10,Furniture,1531.20,1955.56,New,0.00,Credit Card,Online,East-David,7952.11,5229.184121,2722.925879
811,1081,2023-07-14,Eve,North,16,Clothing,2530.15,2568.13,New,0.01,Credit Card,Online,North-Eve,7001.64,4931.882435,2069.757565
76,1054,2023-01-10,Eve,South,40,Furniture,2654.11,2929.32,Returning,0.08,Cash,Online,South-Eve,4634.16,5013.643606,-379.483606
636,1052,2023-01-05,Bob,North,11,Clothing,3451.59,3929.26,New,0.30,Credit Card,Retail,North-Bob,8837.34,5128.550731,3708.789269
973,1003,2023-05-11,Charlie,North,26,Electronics,3418.78,3824.10,New,0.19,Credit Card,Online,North-Charlie,6760.37,5034.950055,1725.419945
938,1090,2023-11-10,Alice,North,16,Clothing,2183.37,2263.36,Returning,0.00,Bank Transfer,Retail,North-Alice,3349.51,5377.183951,-2027.673951
899,1075,2023-01-02,David,West,26,Electronics,4535.38,4557.56,New,0.00,Credit Card,Online,West-David,919.09,5534.549778,-4615.459778
280,1023,2023-04-28,Charlie,North,5,Electronics,2311.25,2482.34,Returning,0.22,Credit Card,Retail,North-Charlie,9850.10,4794.469407,5055.630593
883,1029,2023-08-02,Eve,South,46,Furniture,4609.66,4879.15,Returning,0.30,Cash,Retail,South-Eve,2855.85,5009.289510,-2153.439510
761,1028,2023-08-12,Charlie,South,41,Clothing,3956.03,4163.68,New,0.12,Bank Transfer,Retail,South-Charlie,2490.82,4982.341229,-2491.521229
319,1066,2023-03-28,Charlie,North,7,Clothing,523.42,632.44,New,0.20,Bank Transfer,Online,North-Charlie,7297.86,4915.015987,2382.844013

In [37]:
# ============================================================
# CELL 27 - FINAL MODEL EVALUATION
# ============================================================

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

print("=" * 70)
print("CELL 27 - FINAL MODEL EVALUATION")
print("=" * 70)

# Calculate metrics
final_mae = mean_absolute_error(
    y_test,
    best_predictions
)

final_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        best_predictions
    )
)

final_r2 = r2_score(
    y_test,
    best_predictions
)

print("\nBest Model:")
print(BEST_MODEL_NAME)

print("\nEvaluation Metrics:")
print("-" * 40)

print(f"MAE  : {final_mae:.4f}")
print(f"RMSE : {final_rmse:.4f}")
print(f"R²   : {final_r2:.4f}")

======================================================================
CELL 27 - FINAL MODEL EVALUATION
======================================================================

Best Model:
Gradient Boosting

Evaluation Metrics:
----------------------------------------
MAE  : 2781.8100
RMSE : 3157.6616
R²   : -0.0789

In [38]:
# ============================================================
# CELL 28 - ACTUAL VS PREDICTED GRAPH
# ============================================================

import matplotlib.pyplot as plt

print("=" * 70)
print("CELL 28 - ACTUAL VS PREDICTED")
print("=" * 70)

plt.figure(figsize=(10, 6))

plt.scatter(
    y_test,
    best_predictions,
    alpha=0.6
)

plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")

plt.title(
    f"Actual vs Predicted - {BEST_MODEL_NAME}"
)

plt.grid(True)

plt.tight_layout()

# Save graph
Path("reports").mkdir(exist_ok=True)

plt.savefig(
    "reports/actual_vs_predicted.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()

print("✓ Graph displayed in Jupyter.")
print("✓ Graph saved:")
print("reports/actual_vs_predicted.png")

======================================================================
CELL 28 - ACTUAL VS PREDICTED
======================================================================
✓ Graph displayed in Jupyter.
✓ Graph saved:
reports/actual_vs_predicted.png

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_25004\2443186110.py:39: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [39]:
# ============================================================
# CELL 29 - VERIFY BEST MLFLOW RUN
# ============================================================

import mlflow
from mlflow import MlflowClient

print("=" * 70)
print("CELL 29 - VERIFY BEST MLFLOW RUN")
print("=" * 70)

# Connect to your existing MLflow server
mlflow.set_tracking_uri(
    "http://127.0.0.1:5000"
)

client = MlflowClient(
    tracking_uri="http://127.0.0.1:5000"
)

# Get best run
best_run = client.get_run(
    BEST_RUN_ID
)

print("\nRun ID:")
print(best_run.info.run_id)

print("\nRun Status:")
print(best_run.info.status)

print("\nParameters")
print("-" * 40)

for key, value in best_run.data.params.items():
    print(f"{key}: {value}")

print("\nMetrics")
print("-" * 40)

for key, value in best_run.data.metrics.items():
    print(f"{key}: {value}")

======================================================================
CELL 29 - VERIFY BEST MLFLOW RUN
======================================================================

Run ID:
2a844be6b26647f5b480594adbf99259

Run Status:
FINISHED

Parameters
----------------------------------------
model: GradientBoostingRegressor
test_size: 0.2
random_state: 42
n_estimators: 100
max_depth: 3

Metrics
----------------------------------------
MAE: 2781.810026303327
RMSE: 3157.6615991452873
R2: -0.07893952086367184

In [40]:
# ============================================================
# CELL 30 - MLFLOW MODEL REGISTRY
# ============================================================

import mlflow

print("=" * 70)
print("CELL 30 - MLFLOW MODEL REGISTRY")
print("=" * 70)

# Name that will appear in MLflow Model Registry
REGISTERED_MODEL_NAME = "SalesPredictionModel"

# Model stored inside the best MLflow run
model_uri = (
    f"runs:/{BEST_RUN_ID}/model"
)

print("\nRegistered Model Name:")
print(REGISTERED_MODEL_NAME)

print("\nBest Run ID:")
print(BEST_RUN_ID)

print("\nModel URI:")
print(model_uri)

print("\nRegistering model...")

registered_model = mlflow.register_model(
    model_uri=model_uri,
    name=REGISTERED_MODEL_NAME
)

print("\n✓ MODEL REGISTERED SUCCESSFULLY")

print("-" * 50)

print("Model Name :", registered_model.name)
print("Version    :", registered_model.version)

======================================================================
CELL 30 - MLFLOW MODEL REGISTRY
======================================================================

Registered Model Name:
SalesPredictionModel

Best Run ID:
2a844be6b26647f5b480594adbf99259

Model URI:
runs:/2a844be6b26647f5b480594adbf99259/model

Registering model...

Successfully registered model 'SalesPredictionModel'.
2026/09/01 16:05:08 WARNING mlflow.tracking._model_registry.fluent: Run with id 2a844be6b26647f5b480594adbf99259 has no artifacts at artifact path 'model', registering model based on models:/m-35f7b7f98cbc4c68a0297f54ba7f2922 instead
2026/09/01 16:05:08 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: SalesPredictionModel, version 1
Created version '1' of model 'SalesPredictionModel'.

✓ MODEL REGISTERED SUCCESSFULLY
--------------------------------------------------
Model Name : SalesPredictionModel
Version    : 1

In [41]:
# ============================================================
# CELL 31 - DISPLAY MODEL REGISTRY
# ============================================================

print("=" * 70)
print("CELL 31 - MODEL REGISTRY")
print("=" * 70)

# Search registered model versions
versions = client.search_model_versions(
    f"name='{REGISTERED_MODEL_NAME}'"
)

registry_rows = []

for version in versions:

    registry_rows.append({
        "Model Name": version.name,
        "Version": version.version,
        "Run ID": version.run_id,
        "Status": version.status
    })

registry_df = pd.DataFrame(
    registry_rows
)

display(registry_df)

======================================================================
CELL 31 - MODEL REGISTRY
======================================================================

             Model Name Version                            Run ID Status
0  SalesPredictionModel       1  2a844be6b26647f5b480594adbf99259  READY

In [42]:
# ============================================================
# CELL 32 - LOAD MODEL FROM MLFLOW REGISTRY
# ============================================================

print("=" * 70)
print("CELL 32 - LOAD MODEL FROM REGISTRY")
print("=" * 70)

# Find latest version
latest_version = max(
    versions,
    key=lambda x: int(x.version)
)

# Create registry URI
registry_model_uri = (
    f"models:/{REGISTERED_MODEL_NAME}/"
    f"{latest_version.version}"
)

print("\nRegistry Model URI:")
print(registry_model_uri)

# Load model
registered_model_loaded = mlflow.sklearn.load_model(
    registry_model_uri
)

print("\n✓ Model successfully loaded from MLflow Model Registry.")

======================================================================
CELL 32 - LOAD MODEL FROM REGISTRY
======================================================================

Registry Model URI:
models:/SalesPredictionModel/1

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

✓ Model successfully loaded from MLflow Model Registry.

In [43]:
# ============================================================
# CELL 33 - TEST REGISTERED MODEL
# ============================================================

print("=" * 70)
print("CELL 33 - REGISTERED MODEL PREDICTION TEST")
print("=" * 70)

# Generate predictions from registry model
registry_predictions = (
    registered_model_loaded.predict(X_test)
)

# Calculate metrics
registry_mae = mean_absolute_error(
    y_test,
    registry_predictions
)

registry_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        registry_predictions
    )
)

registry_r2 = r2_score(
    y_test,
    registry_predictions
)

print("\nRegistered Model:")
print(REGISTERED_MODEL_NAME)

print("\nVersion:")
print(latest_version.version)

print("\nPerformance:")
print("-" * 40)

print(f"MAE  : {registry_mae:.4f}")
print(f"RMSE : {registry_rmse:.4f}")
print(f"R²   : {registry_r2:.4f}")

======================================================================
CELL 33 - REGISTERED MODEL PREDICTION TEST
======================================================================

Registered Model:
SalesPredictionModel

Version:
1

Performance:
----------------------------------------
MAE  : 2781.8100
RMSE : 3157.6616
R²   : -0.0789

In [44]:
# ============================================================
# CELL 34 - DISPLAY ALL MLFLOW RUNS
# ============================================================

print("=" * 70)
print("CELL 34 - ALL MLFLOW EXPERIMENT RUNS")
print("=" * 70)

experiment = mlflow.get_experiment_by_name(
    "Sales_Prediction"
)

runs = mlflow.search_runs(
    experiment_ids=[
        experiment.experiment_id
    ],
    order_by=[
        "metrics.R2 DESC"
    ]
)

columns = [
    "run_id",
    "status",
    "params.model",
    "params.test_size",
    "params.random_state",
    "params.n_estimators",
    "metrics.MAE",
    "metrics.RMSE",
    "metrics.R2"
]

available_columns = [
    column
    for column in columns
    if column in runs.columns
]

display(
    runs[available_columns]
)

======================================================================
CELL 34 - ALL MLFLOW EXPERIMENT RUNS
======================================================================

,run_id,status,params.model,params.test_size,params.random_state,params.n_estimators,metrics.MAE,metrics.RMSE,metrics.R2
0,2a844be6b26647f5b480594adbf99259,FINISHED,GradientBoostingRegressor,0.2,42,100,2781.810026,3157.661599,-0.078940
1,8c259ba3e67846bb80a0bf1f927a1bcc,FINISHED,RandomForestRegressor,0.2,42,100,2831.952027,3232.561103,-0.130731
2,a5f3699421364857a425d2511c87b931,FINISHED,LinearRegression,0.2,42,None,3266.472460,3840.218813,-0.595798
3,e6e1b456ce464a389f2ffb8c07c9d60f,FAILED,LinearRegression,0.2,42,None,3266.472460,3840.218813,-0.595798
4,a9c31e831df843f7a232aae46c14581f,FAILED,LinearRegression,0.2,42,None,3266.472460,3840.218813,-0.595798
5,9e199aeb18274da8996883f68fef0adc,FAILED,LinearRegression,0.2,42,None,3266.472460,3840.218813,-0.595798
6,0d7907c58c7e4f0ab989a3008ddc56ab,FAILED,LinearRegression,0.2,42,None,3266.472460,3840.218813,-0.595798
7,709d5f8a624742a38a0f392b3217a070,FINISHED,DecisionTreeRegressor,0.2,42,None,3354.541200,4129.529213,-0.845300
8,b580bda253f34198a1d698d84f8a648c,FINISHED,None,None,None,None,NaN,NaN,NaN

In [45]:
# ============================================================
# CELL 35 - FINAL MLFLOW DASHBOARD
# ============================================================

from IPython.display import HTML, display

dashboard = f"""
<div style="
    font-family: Arial, sans-serif;
    border: 2px solid #444;
    border-radius: 12px;
    padding: 25px;
    margin: 15px 0;
">

<h1>Sales Prediction - MLOps Result</h1>

<h2>MLflow Experiment</h2>

<p>
<b>Experiment:</b> Sales_Prediction
</p>

<p>
<b>Best Run ID:</b> {BEST_RUN_ID}
</p>

<p>
<b>Status:</b> FINISHED
</p>

<hr>

<h2>Best Model</h2>

<p>
<b>Model:</b> {BEST_MODEL_NAME}
</p>

<hr>

<h2>Metrics</h2>

<table style="
    width:100%;
    border-collapse:collapse;
">

<tr>
<th style="border:1px solid #888;padding:10px;">
Metric
</th>

<th style="border:1px solid #888;padding:10px;">
Value
</th>
</tr>

<tr>
<td style="border:1px solid #888;padding:10px;">
MAE
</td>

<td style="border:1px solid #888;padding:10px;">
{BEST_MAE:.6f}
</td>
</tr>

<tr>
<td style="border:1px solid #888;padding:10px;">
RMSE
</td>

<td style="border:1px solid #888;padding:10px;">
{BEST_RMSE:.6f}
</td>
</tr>

<tr>
<td style="border:1px solid #888;padding:10px;">
R²
</td>

<td style="border:1px solid #888;padding:10px;">
{BEST_R2:.6f}
</td>
</tr>

</table>

<hr>

<h2>Parameters</h2>

<table style="
    width:100%;
    border-collapse:collapse;
">

<tr>
<td style="border:1px solid #888;padding:10px;">
Model
</td>

<td style="border:1px solid #888;padding:10px;">
{BEST_MODEL_NAME}
</td>
</tr>

<tr>
<td style="border:1px solid #888;padding:10px;">
Test Size
</td>

<td style="border:1px solid #888;padding:10px;">
{TEST_SIZE}
</td>
</tr>

<tr>
<td style="border:1px solid #888;padding:10px;">
Random State
</td>

<td style="border:1px solid #888;padding:10px;">
{RANDOM_STATE}
</td>
</tr>

</table>

<hr>

<h2>Model Registry</h2>

<p>
<b>Registered Model:</b>
{REGISTERED_MODEL_NAME}
</p>

<p>
<b>Version:</b>
{latest_version.version}
</p>

<hr>

<h2>Artifacts</h2>

<ul>
<li>Trained model</li>
<li>Model comparison CSV</li>
<li>Actual vs Predicted graph</li>
<li>Data profiling HTML report</li>
</ul>

<hr>

<h2>Registry Verification</h2>

<p>
<b>Registry Model R²:</b>
{registry_r2:.6f}
</p>

<p>
<b>Registry Model Status:</b>
Successfully loaded and tested
</p>

</div>
"""

display(
    HTML(dashboard)
)

In [46]:
# ============================================================
# CELL 36 - FINAL PREDICTION OUTPUT
# ============================================================

print("=" * 70)
print("CELL 36 - FINAL SALES PREDICTIONS")
print("=" * 70)

display(
    prediction_df.head(20)
)

======================================================================
CELL 36 - FINAL SALES PREDICTIONS
======================================================================

,Product_ID,Sale_Date,Sales_Rep,Region,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep,Actual,Predicted,Error
521,1100,2023-05-23,Bob,West,29,Food,3559.56,3607.15,Returning,0.21,Cash,Retail,West-Bob,7667.96,5373.761795,2294.198205
737,1031,2023-03-23,Eve,East,32,Clothing,3351.33,3711.47,New,0.16,Cash,Retail,East-Eve,433.40,3916.143807,-3482.743807
740,1003,2023-07-25,Eve,West,5,Food,2206.58,2490.47,New,0.28,Cash,Online,West-Eve,5617.64,4668.237826,949.402174
660,1017,2023-12-23,Alice,East,33,Food,1551.25,1994.01,Returning,0.08,Cash,Online,East-Alice,780.27,4799.410664,-4019.140664
411,1042,2023-05-26,Bob,East,1,Electronics,1406.24,1535.57,New,0.08,Credit Card,Retail,East-Bob,848.28,4522.511394,-3674.231394
678,1017,2023-02-07,Charlie,West,2,Food,728.41,1094.92,New,0.24,Cash,Retail,West-Charlie,7542.30,4461.530613,3080.769387
626,1028,2023-08-31,Eve,North,28,Furniture,2055.28,2449.64,New,0.19,Credit Card,Online,North-Eve,5403.00,4956.913747,446.086253
513,1069,2023-05-29,Alice,North,30,Electronics,300.01,477.68,New,0.11,Bank Transfer,Retail,North-Alice,4494.80,4929.459140,-434.659140
859,1075,2023-06-15,Eve,North,26,Furniture,1749.34,1935.25,New,0.14,Credit Card,Online,North-Eve,9736.49,4931.882435,4804.607565
136,1099,2023-03-04,David,East,10,Furniture,1531.20,1955.56,New,0.00,Credit Card,Online,East-David,7952.11,5229.184121,2722.925879
811,1081,2023-07-14,Eve,North,16,Clothing,2530.15,2568.13,New,0.01,Credit Card,Online,North-Eve,7001.64,4931.882435,2069.757565
76,1054,2023-01-10,Eve,South,40,Furniture,2654.11,2929.32,Returning,0.08,Cash,Online,South-Eve,4634.16,5013.643606,-379.483606
636,1052,2023-01-05,Bob,North,11,Clothing,3451.59,3929.26,New,0.30,Credit Card,Retail,North-Bob,8837.34,5128.550731,3708.789269
973,1003,2023-05-11,Charlie,North,26,Electronics,3418.78,3824.10,New,0.19,Credit Card,Online,North-Charlie,6760.37,5034.950055,1725.419945
938,1090,2023-11-10,Alice,North,16,Clothing,2183.37,2263.36,Returning,0.00,Bank Transfer,Retail,North-Alice,3349.51,5377.183951,-2027.673951
899,1075,2023-01-02,David,West,26,Electronics,4535.38,4557.56,New,0.00,Credit Card,Online,West-David,919.09,5534.549778,-4615.459778
280,1023,2023-04-28,Charlie,North,5,Electronics,2311.25,2482.34,Returning,0.22,Credit Card,Retail,North-Charlie,9850.10,4794.469407,5055.630593
883,1029,2023-08-02,Eve,South,46,Furniture,4609.66,4879.15,Returning,0.30,Cash,Retail,South-Eve,2855.85,5009.289510,-2153.439510
761,1028,2023-08-12,Charlie,South,41,Clothing,3956.03,4163.68,New,0.12,Bank Transfer,Retail,South-Charlie,2490.82,4982.341229,-2491.521229
319,1066,2023-03-28,Charlie,North,7,Clothing,523.42,632.44,New,0.20,Bank Transfer,Online,North-Charlie,7297.86,4915.015987,2382.844013

In [47]:
# ============================================================
# CELL 37 - FINAL PROJECT SUMMARY
# ============================================================

print("\n")
print("=" * 80)
print("       SALES PREDICTION - MLOPS PIPELINE COMPLETE")
print("=" * 80)

print(f"""
DATA
----
Target Column       : {TARGET_COLUMN}
Training Records    : {len(X_train)}
Testing Records     : {len(X_test)}

MODEL TRAINING
--------------
Models Trained      : {len(models)}

BEST MODEL
----------
Model               : {BEST_MODEL_NAME}
MAE                 : {BEST_MAE:.6f}
RMSE                : {BEST_RMSE:.6f}
R²                  : {BEST_R2:.6f}

MLFLOW
------
Tracking URI        : {mlflow.get_tracking_uri()}
Experiment          : Sales_Prediction
Best Run ID         : {BEST_RUN_ID}

MODEL REGISTRY
--------------
Registered Model    : {REGISTERED_MODEL_NAME}
Version             : {latest_version.version}

REGISTRY TEST
-------------
Registry MAE        : {registry_mae:.6f}
Registry RMSE       : {registry_rmse:.6f}
Registry R²         : {registry_r2:.6f}

OUTPUTS
-------
✓ Processed Sales Dataset
✓ Model Comparison
✓ Actual vs Predicted Graph
✓ MLflow Experiment Runs
✓ MLflow Parameters
✓ MLflow Metrics
✓ MLflow Model Artifact
✓ MLflow Model Registry
✓ Registered Model Prediction

STATUS
------
✓ MLOps pipeline completed successfully
""")

print("=" * 80)

================================================================================
       SALES PREDICTION - MLOPS PIPELINE COMPLETE
================================================================================

DATA
----
Target Column       : Sales_Amount
Training Records    : 800
Testing Records     : 200

MODEL TRAINING
--------------
Models Trained      : 4

BEST MODEL
----------
Model               : Gradient Boosting
MAE                 : 2781.810026
RMSE                : 3157.661599
R²                  : -0.078940

MLFLOW
------
Tracking URI        : http://127.0.0.1:5000
Experiment          : Sales_Prediction
Best Run ID         : 2a844be6b26647f5b480594adbf99259

MODEL REGISTRY
--------------
Registered Model    : SalesPredictionModel
Version             : 1

REGISTRY TEST
-------------
Registry MAE        : 2781.810026
Registry RMSE       : 3157.661599
Registry R²         : -0.078940

OUTPUTS
-------
✓ Processed Sales Dataset
✓ Model Comparison
✓ Actual vs Predicted Graph
✓ MLflow Experiment Runs
✓ MLflow Parameters
✓ MLflow Metrics
✓ MLflow Model Artifact
✓ MLflow Model Registry
✓ Registered Model Prediction

STATUS
------
✓ MLOps pipeline completed successfully

================================================================================